config/routes.rb
Rails.application.routes.draw do
  root 'states#index'
  devise_for :users
  resources :users, only: [:show]

  namespace :admin do
      resources :petitions, only: [:index, :destroy]
      resources :users, only: [:edit, :update, :destroy]
  end

  resources :states, only: [:show] do
    resources :petitions
  end

  resources :petitions, only: [:show, :index] do
    resources :memberships, only: [:create, :destroy]
  end
end

app/models/civic_api.rb
class CivicAPI
  def civic_api_call(params)
    if params.include?(" ")
      params = params.delete(' ')
      url = "https://www.googleapis.com/civicinfo/v2/representatives?key=#{ENV["GOOGLE_KEY"]}&address=#{params}"
    else
      url = "https://www.googleapis.com/civicinfo/v2/representatives?key=#{ENV["GOOGLE_KEY"]}&address=#{params}"
    end

    uri = URI.parse(url)
    @state_info = JSON.parse(Net::HTTP.get(uri))

    parse(@state_info)
  end

  def parse(state_info)
      rep = []
      info = {}
      counter = 0
    state_info["officials"].each do |official|
        info["name"] = official["name"]
        if official["address"]
          info["address1"] = official["address"][0]["line1"]
          info["address2"] = official["address"][0]["line2"]
          info["city"] = official["address"][0]["city"].capitalize
          info["state"] = official["address"][0]["state"]
          info["zip"] = official["address"][0]["zip"]
        end
        info["party"] = official["party"]

        unless official["phones"].nil?
          info["phones"] = official["phones"].join
        end

        unless official["urls"].nil?
          info["url"] = official["urls"].join
        end

        info["index"] = counter

        info.delete_if {|k,v| v == nil}
        rep.push(info.dup)
        counter += 1
    end
      return rep
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition

  validates :user, presence: true
  validates :petition, presence: true
  validates :user, uniqueness: { scope: :petition }
end

app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :state
  has_one :owner, class_name: "User", foreign_key: "owner_id"
  has_many :memberships
  has_many :users, through: :memberships
  mount_uploader :image, PetitionPhotoUploader

  validates :name, presence: true
  validates :description, presence: true
  validates :owner_id, presence: true
  validates :state_id, presence: true

  def self.search(search)
    if search
      where(["name ILIKE ?", "%#{search}%"])
    else
      all
    end
  end

  def self.state_search(search, state)
    if search
      where(["name ILIKE ?", "%#{search}%"]).where(state: state)
    else
      where(state: state).limit(10)
    end
  end

  def self.top_petitions
    select("petitions.*, count(memberships.id) AS signatures_count").
    joins(:memberships).
    group("petitions.id").
    order("signatures_count DESC").
    limit(4)
  end

  def owner?(owner_id)
    "#{User.find(owner_id).first_name} #{User.find(owner_id).last_name}"
  end

  def signature_count
    memberships.count
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :petitions
  has_many :state_word_counts

  validates :name, presence: true, uniqueness:true

  def to_param
    name
  end
end

app/models/state_word_count.rb
class StateWordCount < ActiveRecord::Base
  belongs_to :state
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :petitions, through: :memberships
  mount_uploader :image, ProfilePhotoUploader

  ROLES = %w(member admin)

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :role, presence: true, inclusion: { in: ROLES }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/petitions_controller.rb
class Admin::PetitionsController < ApplicationController
  before_action :authenticate!

  def index
    @petitions = Petition.limit(20)
  end

  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy
    redirect_to admin_petitions_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :devise_permitted_parameters, if: :devise_controller?

  protected

  def devise_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation, :image, :affiliation)
    end

    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :username, :email, :password_confirmation, :current_password, :image, :affiliation)
    end
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = 'You need to sign in if you want to do that!'
      redirect_to root_path
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def create
    @membership = Membership.new(user_id: params[:user], petition_id: params[:petition_id])
    if @membership.save!
      redirect_to state_path(id: params[:id]), notice: "You've signed this petition!"
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    redirect_to user_path
  end

end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  def index
    @state = State.find_by(name: params[:state_id])
    @petition = Petition.new

    if params[:search]
      @petitions = Petition.search(params[:search])
    else
      @petitions = Petition.page(params[:page]).
      per(3)
    end
  end

  def new
    @petition = Petition.new
  end

  def create
    @state = State.find_by(name: params[:state_id])
    @petition = @state.petitions.new(petition_params)
    @petition.owner_id = current_user.id


    if @petition.save
      redirect_to state_path(@state), notice: "Added."
    else
      redirect_to state_path(@state), notice: "Not valid. Please provide a name and description."
    end
  end

  def show
    @petition = Petition.find(params[:id])
    @state = State.find_by(name: params[:state_id])
  end

  def edit
    @petition = Petition.find(params[:id])
    @state = State.find_by(id: params[:state_id])
  end

  def update
    @petition = Petition.find(params[:id])
    @petition.update_attributes(petition_params)
    if @petition.save
      redirect_to user_path, notice: "Petition updated!"
    else
      @errors = @petition.errors.full_messages
      render :edit
    end
  end

  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy
    redirect_to user_path
  end

  def petition_params
    params.require(:petition).permit(:name, :description, :image)
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def show
    @state = State.find_by(name: params[:id])

    state_representatives = CivicAPI.new
    @state_info = state_representatives.civic_api_call(params[:id])

    @petitions = Petition.state_search(params[:search], @state).
      page(params[:page]).
      per(3)

    respond_to do |format|
      format.json { render json: @state.state_word_counts, each_serializer: StateWordCountSerializer }
      format.html
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @owned_petitions = Petition.where(owner_id: @user.id)
    @signed_petitions = @user.petitions
  end
end

app/views/admin/petitions/index.html.erb
<% if @petitions %>
  <% @petitions.each do |petition| %>
    <div class="inline-list" id="admin_petitions">
      <li><%= petition.name %></li>
      <div class="button">
        <li><%= link_to 'Delete Petition', admin_petition_path(petition), method: :delete %></li>
      </div>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citizen</title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <section class="top-bar-section">
      <% if params[:id] && @state %>
        <h4 id="logo"><a href="/states/<%= @state.name %>"><%= @state.name %></a></h4>
      <% else %>
        <h4 id="logo"><a href="/">Citizen</a></h4>
      <% end %>

      <ul class="right">
        <%- if current_user.try(:admin?) %>
         <li><%= link_to 'Admin Home', admin_petitions_path %></li>
       <%- end %>
        <%- if current_user -%>
          <li><%= link_to 'Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>

    <section class="top-bar-section">
      <ul class="left">
        <% if params[:id] %>
          <li id="side_logo"><h3><a href="/">C</a></h3></li>
          <li><%= link_to 'National Petitions', petitions_path %></li>
        <% elsif params[:id] && @state %>
          <li><a href="#petitions_div"><%= params[:id] %> Petitions</a></li>
        <% else %>
          <li><%= link_to 'National Petitions', petitions_path %></li>
        <% end %>
      </ul>
    </section>
  </nav>


    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= yield :extra_footer %>

</body>
</html>

app/views/petitions/_new.html.erb
<div class="small-6 small-centered columns">  
  <%= form_for [@state, @petition || Petition.new] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit "Submit", class: "small button radius" %>
  <% end %>
</div>

app/views/petitions/edit.html.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<div class="small-12 columns">
  <%= form_for [@state, @petition] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :image %>
    <%= f.file_field :image %>

    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/petitions/index.html.erb
<div class="small-12 columns" id="petition_heading">

  <h1>All Petitions</h1>

  <div class="small-8 small-centered columns" id="petitions_index">
    <div class="row collapse">
      <div class ="inline-list">
      <%= form_tag petitions_path, method: :get do  %>
        <div class="small-9 columns">
          <%= text_field_tag :search %>
        </div>
        <div class="small-3 columns">
          <%= submit_tag "Search Petitions", class: "small button radius" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

  <div class="small-10 small-centered columns" id="all_petitions">
    <% @petitions.each do |petition| %>
      <div class="panel" id="petitions">
        <%= image_tag petition.image.url, size: '150x150' %>
        <h4><%= link_to petition.name,
          state_petition_path(id: petition, state_id: petition.state) %></h4>
        <p><%= petition.description %></p>
        <hr>
        <p>Created by: <%= petition.owner?(petition.owner_id) %></p>
        <p>Signatures: <%= petition.signature_count %></p>
        <%  if current_user %>
          <div class="button small radius">
            <%= link_to 'Sign Petition', petition_memberships_path(petition_id: petition.id,
                  user: current_user.id, id: petition.state), method: :post %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div id="paginator">
      <%= paginate @petitions %>
    </div>
  </div>
</div>

app/views/petitions/show.html.erb
<div class="small-12 columns" id="petition_page">
  <h1><%= @petition.name %></h1>
  <%= image_tag @petition.image.url, size: "300x300" %>
  <p><%= @petition.description  %></p>

  <% if !current_user.nil? && !@petition.users.include?(current_user) %>
    <div class="button small radius">
      <%= link_to 'Sign Petition', petition_memberships_path(petition_id: params[:id],
            user: current_user.id, state: @petition.state), method: :post %>
    </div>
  <% end %>

  <h4>Signatures</h4>
  <div class="small-12 columns">
    <% if @petition.users.include?(current_user) %>
      <% @petition.users.each do |name| %>
        <li><%= name.first_name %> <%= name.last_name %></li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/states/_show.js.erb
$('#all_petitions').html('<%= escape_javascript render(@petitions) %>');
$('#paginator').html('<%= escape_javascript(paginate(@petitions, remote: true).to_s) %>');

app/views/states/index.html.erb
<div class="vmap"></div>

<% content_for :extra_footer do %>
  <script>
    $(function(){
      buildMap();
    });
  </script>
<% end %>

app/views/states/show.html.erb
<div class="small-8 small-centered columns" id="title">
  <h1>Do your reps care about your interests?</h1>
  <p>Check out how frequently <%= @state.name %> representatives use the words below in Congress.</p>
</div>

<hr class="page_break">

<div id="state_chart"></div>

<hr class="page_break">

<div id="petitions">
  <div class="row">
    <div class="large-12 columns" id="popular_petitions">
      <div class="row">
        <h1>Most Popular Petitions in <%= @state.name %></h1>
        <% @petitions.top_petitions.each do |petition| %>
          <div class="large-3 small-6 columns" id="petition_carousel">
            <div class="panel">
              <%= image_tag petition.image.url, size: '150x150' %>
              <h4><%= link_to petition.name,
              state_petition_path(id: petition, state_id: petition.state) %></h4>
              <hr>
              <p>Created by:</p>
              <p><%= petition.owner?(petition.owner_id) %></p>
              <p>Signatures: <%= petition.signature_count %></p>
              <% if current_user && !petition.users.include?(current_user) %>
                <div class="button small radius">
                  <%= link_to 'Sign Petition', petition_memberships_path(petition_id: petition.id,
                        user: current_user.id, id: petition.state), method: :post %>
                </div>
              <% elsif petition.users.include?(current_user) %>
                <div class="button small radius">
                   You've signed!
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% if current_user %>
  <hr>
  <div id="form">
    <div id="new_petition"><i class="fi-clipboard-pencil"></i></div>

    <div class="small-12 columns" id="petition_form">
      <%= render 'petitions/new' %>
    </div>
  </div>
  <hr>
<% end %>

  <div class="small-10 small-centered columns" id="all_petitions">
    <% @petitions.each do |petition| %>
    <div class="panel" id="petitions">
        <%= image_tag petition.image.url, size: '150x150' %>
        <h4><%= link_to petition.name,
          state_petition_path(id: petition, state_id: petition.state) %></h4>
        <p><%= petition.description %></p>
        <hr>
        <p>Created by: <%= petition.owner?(petition.owner_id) %></p>
        <p>Signatures: <%= petition.signature_count %></p>
        <%  if current_user %>
          <div class="button small radius">
              <%= link_to 'Sign Petition', petition_memberships_path(petition_id: petition.id,
                  user: current_user.id, id: petition.state), method: :post %>
          </div>
        <% end %>
    </div>
    <% end %>
    <div id="paginator">
      <%= paginate @petitions %>
    </div>
  </div>
</div>
</div>
<hr class="page_break">
<div class="small-12 columns" id="state_info">
<div class="small-6 columns" id="_vit"></div>
  <div class="small-6 columns" id="rep_info">
    <ul id="civic_info">
      <h2><%= @state.name %> Representatives</h2>
      <hr>
        <% @state_info.each do |official| %>
          <% official.each do |k,v| %>
          <% if v.is_a? String %>
            <li><%= v %></li>
          <% end %>
          <% end %>
          <hr>
        <% end %>
    </ul>
  </div>
</div>

<% content_for :extra_footer do %>
<script type="text/javascript" src="https://voter-info-tool.appspot.com/js/loader.js"></script>
  <script>
    $(function() {
      buildVisualization();
    });
    vit.load({'region': '<%= @state.name %>'});
  </script>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <div class="small-12 columns" id="header">
    <div class="small-4 columns">
      <%= image_tag @user.image.url, size: "60x60" %>
      <h4><%= "#{@user.first_name} #{@user.last_name}" %></h4>
      <p><%= @user.username %></p>
    </div>

  <div class="small-8 columns">

    <% @owned_petitions.each do |petition| %>
      <div class="inline-list" id="owner_petitions">
        <li><%= petition.name %></li>
        <div class="button small radius">
          <%= link_to "Edit Petition", edit_state_petition_path(id: petition, state_id: petition.id) %>
        </div>
        <div class="button small radius">
          <%= link_to "Delete Petition", state_petition_path(id: petition, state_id: petition.id), method: :delete %>
        </div>
      </div>
      <% end %>

      <% @signed_petitions.each do |petition| %>
        <div class="inline-list" id="signed_petitions">
          <li><%= petition.name %></li>

          <div class="button small radius">
            <%= link_to "Delete Signature",
              petition_membership_path(petition, petition.memberships.find_by(user: current_user)), method: :delete %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>